/**
 * @module local-engine — Core
 * SCAFFOLD — Core utilities and configuration for the local-engine.
 */

/** Pipeline state machine — valid transitions */
export const VALID_TRANSITIONS: Record<string, string[]> = {
  DRAFT: ['IMPORTED'],
  IMPORTED: ['PROXY_GENERATED', 'FAILED'],
  PROXY_GENERATED: ['AUDIO_EXTRACTED', 'FAILED'],
  AUDIO_EXTRACTED: ['TRANSCRIBING', 'FAILED'],
  TRANSCRIBING: ['TRANSCRIBED', 'FAILED', 'CANCELLED'],
  TRANSCRIBED: ['ALIGNING_WORDS', 'EDITING', 'FAILED'],
  ALIGNING_WORDS: ['ALIGNED', 'FAILED', 'CANCELLED'],
  ALIGNED: ['AUTO_CUT_ANALYZING', 'EDITING'],
  AUTO_CUT_ANALYZING: ['AUTO_CUT_READY', 'FAILED', 'CANCELLED'],
  AUTO_CUT_READY: ['EDITING'],
  EDITING: ['PRESET_APPLIED', 'BROLL_PLANNING', 'CAPTIONS_GENERATING', 'REFRAMING', 'EXPORTING', 'POST_PRODUCTION_READY'],
  PRESET_APPLIED: ['EDITING', 'BROLL_PLANNING', 'CAPTIONS_GENERATING'],
  BROLL_PLANNING: ['BROLL_READY', 'FAILED', 'CANCELLED'],
  BROLL_READY: ['EDITING', 'CAPTIONS_GENERATING'],
  CAPTIONS_GENERATING: ['CAPTIONS_READY', 'FAILED', 'CANCELLED'],
  CAPTIONS_READY: ['EDITING', 'REFRAMING', 'POST_PRODUCTION_READY'],
  REFRAMING: ['REFRAMED', 'FAILED', 'CANCELLED'],
  REFRAMED: ['EDITING', 'POST_PRODUCTION_READY'],
  POST_PRODUCTION_READY: ['EXPORTING', 'EDITING'],
  EXPORTING: ['EXPORTED', 'FAILED', 'CANCELLED'],
  EXPORTED: ['EDITING'],
  FAILED: ['EDITING', 'DRAFT'],
  CANCELLED: ['EDITING', 'DRAFT'],
};

/** Configuration defaults */
export const ENGINE_DEFAULTS = {
  whisperModel: 'medium',
  proxyResolution: '720p',
  proxyCodec: 'h264',
  maxConcurrentJobs: 2,
} as const;
